metadata:
  items:
  - key: gce-container-declaration
    value: |
      # DISCLAIMER:
      # This container declaration format is not a public API and may change without
      # notice. Please use gcloud command-line tool or Google Cloud Console to run
      # Containers on Google Compute Engine.

      spec:
        containers:
        - env:
          - name: GOOGLE_PROJECT_ID
            value: mgcp-1039568-risd-web-prod
          - name: GOOGLE_SERVICE_ACCOUNT
            value: sva-risd-webhook01@mgcp-1039568-risd-web-prod.iam.gserviceaccount.com
          - name: GOOGLE_KEY_JSON_STRING
            value: '{"type":"service_account","project_id":"mgcp-1039568-risd-web-prod","private_key_id":"24c7a8fc73c135a1a55f396f8c1eacfa5866de59","private_key":"-----BEGIN
              PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwttvoE0UXaIj2\n/om3GWchuDw0kui6Y/4NDCdHRh4Izg6jmdn0cJavYhB1Uy+WFVB+pMeDN+mc5bQx\nGBRxn9Kr35PF/DZNBIBKMimAeN3tzQrsVDV1ZR2rjiEaSwEU34qmK4MCaPWy8a7z\nE3ts/ECK4wHC99d9FSn4+5oy0AjGMG23du0CrJjYQCRvEGamkWJdM0JDx0aPI99D\nK2qPYSWA22bhsZjBjcLYJKYHARkms+p/rJeCFaFb/Vw8cEvocOuHLRGVNWWgIm+K\nIf0LQXavhwYQxNvwxasFMMQn+0qzGWjSEhM75arXXULl+KAIuV+Gowaadtjgakhc\nfuMo0u5TAgMBAAECggEAMWJ45Et2VItfM3+A5w2PV8oP8TVZGrXVCrppw65huF41\nkxzs3zYTtmG2bcNYmh3MyAeuxgn7HGDJUasEE5jxnBy4RG0uk6l9XL7WAFRG2S0j\nL1Z9NhiTCR2IPLvXSokKS1P/oc3JVD/cf4vjQ1rfgrDcDiuLKiae+zj9J9Qhj5kD\n4Duud1yz1GCoLzUu9fdcRUfsVzEGbta7IhohV/cdhrAWnqXeDWvM/jRnicu9jci7\noyP6XsbIK//I7x7zdGxebPfrm6NcHosEJI24H7+hXuOl++H+4F2NtiKPJt0QV3Bs\npYCuP5uOEQzbuKR3oxsk+gRnkgpCUJwqjTPcssNQmQKBgQDmJKP6DV9VvnDvtaEQ\n6kkPaywvCs8P9y0+mMVjJbOttdRYfvhBrb85692V8BhtEWaF+xkBbX+1w4dTddMm\ncSNr69KklQY17nxLaEk3o/x0IsDCcNYcCwK938aoIEQoWLnYmkhPabhltCs4mOrl\n5DboEtDkEKv8Eo8IqfCZHTppfQKBgQDEkYCY3zNqMfEiwEPK0uhkb7nBl3eVIEjm\ndUs92rG11Bcnc4EZMcbejLwrv5Y6M0Qs7kCticy9wIWCKKP1mfg8tIzOmT1ZWT0a\nkEWXYe79dGzZ5AD+Zn0/MvgP59foqQ56XzbkQk7ZTkL00wpXM3f/CHQV1yIJMuhp\n2UvFar3ADwKBgCoHBurjBkXiQT2FLaSpJC5so+TzVFzWBq0nuOQiPm26hsyiYzOb\nRxCMwipfbhZ81vwgnrBkDq5ixpO3MJgUkSNkLVNg44F1y7z5jmVazP9oWUsoz/DP\nEfEarGyHd+rmSQoFIq9d3w6zmDD9u+e/hUdcKEl9weqGeRhb8FQFwmUBAoGAf14M\nZoHRzdC4f5z3EFgiztl6Eo+zo4Q82F9ONrEbD0dzDVQRZaLUSmYEk5BbpjCLz1U9\nwXSVnqo9l/3/Z2ex6pvO1RuEHf3t0uWCwjlp4v7qfTD4197O7wF2rM+8HfxU7kP9\nzF+Ouc21IvAQNjqaWT1AAtrYKf+7isKLD0s/0k8CgYEAteTx+dmEgj/Nkp2MvsJF\nZIPvMDnS8dC7bJWRx7xrIbWxSokJa7tCeoYgYBRt45DuyrOeBG5jV1xHyrT6yMRJ\n4cavgPNMB8c+t6jZY6Q+9xryoSOYOmNlp8Vu8s6qeQtQlA+qEbK26U7l4uf/vtdb\nO9kYkgy3iqvzM9mGp6GxwSY=\n-----END
              PRIVATE KEY-----\n","client_email":"sva-risd-webhook01@mgcp-1039568-risd-web-prod.iam.gserviceaccount.com","client_id":"107762002521166068549","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://accounts.google.com/o/oauth2/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/sva-risd-webhook01%40mgcp-1039568-risd-web-prod.iam.gserviceaccount.com"}'
          - name: GOOGLE_BUCKET_DEFAULT_CORS
            value: '[{"origin":["*.risd.systems","cdn.risd.systems","risd.edu","*.risd.edu","localhost"],"responseHeader":["Content-Type"],"method":["GET","HEAD","OPTIONS"],"maxAgeSeconds":3600}]'
          - name: DEVELOPMENT_DOMAIN
            value: risd.systems
          - name: MAILGUN_SECRET_KEY
            value: key-781868dbe03fe24a80a96bf5129ff19b
          - name: MAILGUN_DOMAIN
            value: risd.systems
          - name: FROM_EMAIL
            value: postmaster@risd.systems
          - name: REPLY_EMAIL
            value: mgdevelopers@risd.edu
          - name: FIREBASE
            value: risd-webhook
          - name: FIREBASE_SERVICE_ACCOUNT_KEY
            value: service-accounts/risd-webhook-firebase-adminsdk-wzu6s-97c3923736.json
          - name: FIREBASE_SERVICE_ACCOUNT_KEY_STRING
            value: '{"type":"service_account","project_id":"risd-webhook","private_key_id":"97c3923736958c149e473b3e02e26dd05e1d46c8","private_key":"-----BEGIN
              PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCwO23ZFoJrZCYz\nw93QcXJngpvZs0Yw0pOr1wBPDfDC9SCTMgqNeAuy7a6y/AKGDWIifk0e2aE2zptV\n1W7ogSuTYBBtR6WFiS8qiBVOVjird3xSkRuv2ZtfQpDKpimUozuPVJnWDvvd15pW\nEvz9uf9XsDleYV8SArTQgTxWw5C975Q0X22NJ8K9/5j5R+1rBCAfMFvCQttzDn47\noRpZM8yrD9EhakTeX+uH5fTcH4X1+VHC056/1QxFZU164VPiLcWSRaejukRiXAr/\nnhOanV+t4PrI2yP5UWnOz1ddMeNkbHXFDl+egylmEy0zIhjNvGbFmQ9zSdZOgk2W\nxmRS/5oXAgMBAAECggEAASqI1zc96ltW9rVkwgdY0XSHdtD9NZTUeKj14zqyuCeK\nbU7sdkkwEqFeAZMx/78WQieBzSLK3U5QBX5huyoiUVmrt31ni/2qETxQn8cUSEDZ\n0sC2ZTB/GwnuuViQzTSopTx9vsaJ8MrcxkBelN3mjFGp34UCGGAU4DhVX4xFvewA\nG8ZFy99BcE1hPU2OkWRKUQy71qO519Zvb5xcmssEF9ju6G+UFZPA4UjPdL9X4ykJ\nfhPDJSbybuU5XA+4SD8EaZSW0APK7yVmK7rhGOOYixn6+7NB1j9Yiac+alt3bXnz\nY95DHWsz43pgCnWzdXmuQ2KyIWCJpmySd9l3rVYuIQKBgQDky+aTKkZ92WlOOUIl\nwJppUWLINJvyFSFZWdetClOaSpRAuIzmXCsEgemXXKas3fgdZZCXP/FG+9XYH5Wv\ny4fKTCTXtMseg/+n8H6q7IYizLysCAyxUZ8TCtseIgZg1KQ8ficW+UTErgi04wOX\nUnnJ2oSIau6uIZW+SQ1D5le50QKBgQDFL5OrqnljEC5GBJ6NDtmnDuedwwmaU1VF\nhNVNiVgZEvBk5uewE7d8Wcvqc2QCULg13vsTjZv/OzOcvT2qAv2/Gj9G0guDXwy0\nP+R6uRgpxkS5l4oMO4+jHQYW1bSXD0N7TWfJIQW9D6U4Q0jcFtMAP7dYv4y6M+Bs\nbELAtlUnZwKBgGG7w+vbZC9AHt6eUOZFhvA0Jsk0x+S6J/u+CAZP4fSHpRqcevuw\nJWQQhpL0rfIsA1+zUfd6Bfv3eZqPq2Zjv8anjhlijl2jryKy9bjXvljBMlseOSXJ\novUEbyNJD4ZvbxS0IsiKhFirquZyDsemIIYcRP7tBrX1fLzDAdqeW5zxAoGAC4L1\nigYPxBrDuM64Ot/tEPWry+gA/YNz7PUORtKH1B7o7dsVF5BvG9FaODu4UPJJbsuv\nuLqBqurX3oSlvvEhwzBTFV1Z0reP1E4OlqOLp5StmnAgXQp1Hj6phle/jToU5HPm\nZTWKUjlBmgFDlaW3d8JAf+ve2VgB+BJx6zI50m0CgYEAw2Y4pITQlgCuFYUTdkCH\nj/gVa+0Rk0VbpHTfllydngO8KxsK3Q8iXaCxYLNdADeK66t/nFzHC9XAbwIT/EJ/\neJFecJLM/IJCULYf2DDhnDjdtMx6BYOx76DMjTVRsJrg6FYOoeRZNtQuOgBACrqf\nio5f4C+Zims9450zDpRTDv4=\n-----END
              PRIVATE KEY-----\n","client_email":"firebase-adminsdk-wzu6s@risd-webhook.iam.gserviceaccount.com","client_id":"104432707022517158109","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-wzu6s%40risd-webhook.iam.gserviceaccount.com"}'
          - name: SITES_BUCKET
            value: 141566546066-risd-webhook-sites-production
          - name: BACKUPS_BUCKET
            value: 141566546066-risd-webhook-backups-production
          - name: UPLOADS_BUCKET
            value: cdn.risd.systems
          - name: CLOUDFLARE_EMAIL
            value: mgdevelopers@risd.edu
          - name: CLOUDFLARE_KEY
            value: 395b8c8ce1ae9301e5b40d32b696514b52147
          - name: CLOUDFLARE_DOMAINS
            value: "'[{\"domain\": \"!*risd.systems\", \"cname\": \"nonssl.global.fastly.net\"\
              }]'"
          - name: FASTLY_TOKEN
            value: be840fd9485af0b5fa020ba1b9677e25
          - name: FASTLY_SERVICE_ID
            value: 5KXVgxGpFmKQGxI7vdTMKE
          - name: FASTLY_DOMAINS
            value: '[{"domain": "*risd.edu", "address": "https://151.101.2.217", "forceSSL":
              true}, {"domain": "!*risd.systems", "address": "http://151.101.0.204", "forceSSL":
              false}]'
          - name: BUILDER_MAX_PARALLEL
            value: '10'
          - name: ELASTIC_SEARCH_SERVER
            value: https://1d20edb201cc47efb44bc01c7f588784.us-east-2.aws.elastic-cloud.com:443
          - name: ELASTIC_SEARCH_API_KEY
            value: RFJSdzE1RUJGb21MSEtROUdFQjQ6V2xBQTI4SXlUMDZKOHRRLUxDRXpMQQ==
          - name: WEBHOOK_SERVER_PORT
            value: '3000'
          - name: WEBHOOK_SERVER_HOST
            value: 0.0.0.0
          - name: MEMCACHED_SERVERS
            value: '["localhost:11211"]'
          - name: BEANSTALK_SERVER
            value: localhost:11300
          image: us-central1-docker.pkg.dev/risd-media-webhook/risd-webhook-server/risd-webhook-prod:v3.0.3
          name: risd-webhook-instance-prod-v3-0-3
          securityContext:
            privileged: false
          stdin: false
          tty: false
          volumeMounts: []
        restartPolicy: Always
        volumes: []
  - key: google-logging-enabled
    value: 'true'